services:
  quiz-app:
    image: quiz:latest 
    container_name: quiz-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
